<Project>
  <PropertyGroup>
    <LangVersion>latestmajor</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RepositoryUrl>https://github.com/KiarashMinoo/PasswordGeneratorCLI</RepositoryUrl>
  </PropertyGroup>
  <PropertyGroup Label="Nuget">
    <Version>1.0.2</Version>
    <Authors>Kiarash Minoo</Authors>
    <Description>Cryptographically secure, customizable password generation for .NET.</Description>
    <RepositoryUrl>https://github.com/KiarashMinoo/PasswordGeneratorCLI</RepositoryUrl>
  </PropertyGroup>
</Project>