<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageId>PasswordGenerator</PackageId>
        <Version>1.0.0</Version>
        <Authors>Kiarash Minoo</Authors>
        <Description>Cryptographically secure, customizable password generation for .NET.</Description>
        <PackageTags>password;security;cryptography;generator</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIconUrl>icon.png</PackageIconUrl>
        <RepositoryUrl>https://github.com/KiarashMinoo/PasswordGeneratorCLI</RepositoryUrl>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath=""/>
    </ItemGroup>
</Project>